### ISSUE TITLE
Upgrade to the latest Omeka S version?

### ISSUE THREAD

**Issue by tzere** [digirati-co-uk/madoc-platform#56]
Madoc platform seems to be using its own copy of Omeka S. If one wants to upgrade to the latest Omeka S version, would that be possible, and if so, how?

**Comment by stephenwf** [comment]
At the moment we're running the latest v1.3.0 Omeka, and we are aiming to try and keep the fork maintained as much as possible. We're using Docker to build the base Omeka container, so you can change that to build directly from Omeka if you require that. However, here is the list of changes we've made to our fork that we've not yet put back upstream into Omeka:

- PHP 7.2 compatibility (and minimum for our modules)
- Doctrine upgrade
- Non-fatal errors so you can better serve error pages to users
- Logging on by default, pointing to `stdout`
- Scalability of Omeka jobs

While these changes are not required by Madoc, it helps to have them!

You can find out general purpose Omeka docker container here:
https://github.com/digirati-co-uk/madoc-omeka-s/blob/master/Dockerfile

This accepts a few environment variables that you can set when building, including Omeka-s to point to. You can build this container using:
```
OMEKA_FORK=omeka
OMEKA_BRANCH=v1.3.0
```

This will get the tools included in Madoc without the modules. You can see the `Dockerfile` in this repository and see the few lines it takes to get up and running from the base. Just copy in the modules and run `madoc-installer`

This is not the smoothest process at the moment, and our modules do rely on some of the changes we've made, especially the scalability changes for importing large amounts of IIIF content. Our [fork](https://github.com/digirati-co-uk/omeka-s), [Docker build](https://github.com/digirati-co-uk/madoc-omeka-s) and [the platform itself](https://github.com/digirati-co-uk/madoc-platform) are open source, and happy to hear ideas for making this process smoother!

**Comment by pdpotter** [comment]
Thank you for the detailed info. It was a bit confusing, because of the date of the latest [releases](https://github.com/digirati-co-uk/omeka-s/releases) and the dates of the latest commits to the [develop](https://github.com/digirati-co-uk/omeka-s/commits/develop) and [master](https://github.com/digirati-co-uk/omeka-s/commits/master) branches on the fork. Seeing the [7.2-rebase-1.3.0](https://github.com/digirati-co-uk/omeka-s/tree/bugfix/7.2-rebase-1.3.0) branch, everything makes a lot more sense.

Having all or at least some of the changes put back upstream would make the fork unnecessary (at least until the next required deviation) or more easily maintainable and transparant.
